development:
  host: localhost
  database: ue_development

test:
  host: localhost
  database: ue_test

# set these environment variables on your prod server
production:
  host: localhost
  #port: 
  #username: 
  #password: 
  database: ue
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
